### ISSUE TITLE
How is the project for production?

### ISSUE THREAD

**Issue by lowercase00** [bprinty/Flask-Execute#23]
Hello there. Thanks a lot for the package, found it after having a lot of headache with Celery and Flask in a containerized application. I was wondering how do you feel about the maturity of the project, and if could be used for production.

Also, it's quite surprising that the project has only 8 stars while Celery has 16.5k and there's definitely a huge overlap between Flask and Celery users. From a popularity perspective - that should greatly enhance the project's maturity and reliability I would just call is **Flask-Celery**. I understand that this is a bit more opinionated, adding a few functionalities, but I think that would still make sense.

I'll definitely give it a go, but having a project running in production, I have to say that I'm a bit worried about the lack of users.

Anyways, thanks a lot!

**Comment by bprinty** [comment]
I think the project is stable enough for use in a production context. It's just a simplification wrapper over what Celery already provides, so it doesn't add a significant amount of additional complexity to a project. I also actively maintain it and address issues that users submit via GitHub, so there will be support if the need arises. I've personally used it in production applications and haven't run into any issues.

I think there are two primary reasons why it's not as popular: 1) it's a relatively new package, and 2) I haven't done anything to advertise it. I'm sure if I asked the maintainers of an [Awesome-Flask](https://github.com/humiaozuzu/awesome-flask) repo to include it, the package would become more popular. Feel free to spread the word if you find this package useful! The more popular it is, the more the project can grow and evolve in the right ways.

Finally, I would have used `Flask-Celery`, but it was unfortunately already taken by another python package. If the owner of that package is willing to donate the name to this project, I'd be happy to change the name (I agree, it's much better).

**Comment by lowercase00** [comment]
Awesome, well thanks a lot for the effort mate, l was really surprised at how hard it was to use celery with Flask - I could do the basics, but as soon as I needed to integrate it in my docker-compose, push application context, and having to refactor to pre-register tasks, things started to get really messy really fast, it seems that the Django community embraced it a lot more than Flasks'.

I wonder why people think that a package is not necessary, I see it similar do SQLAlchemy, it's not necessary, but make your like a whole lot easier indeed! I will definitely suggest Awesome-Flask to add the package, and will be sending a message to the maintainers of Flask-Celery to see if they could donate the name, even possibly merge some aspects of the project could be a good idea.

Anyways, thanks again, will spend the next few days playing around to see how can I improve my project with this package! Cheers

**Comment by bprinty** [comment]
Totally agree! SQLAlchemy rocks.

Thanks for all the support! I'm glad this package is helping you out. Feel free to stay in touch for any feature requests you might need.
